# Funding para SARDIN-AI

github: []
patreon: # username
open_collective: # username
ko_fi: # username
tidelift: # package-name
community_bridge: # project-name
liberapay: # username
issuehunt: # username
lfx_crowdfunding: # project-name
polar: # username
buy_me_a_coffee: # username
custom:
  - https://sardin-ai.com/donate
