import { useEffect, useState } from 'react';
import { useMaritimeDatabase } from '@/hooks/useMaritimeDatabase';
import { useToast } from '@/hooks/use-toast';

interface DataSeederProps {
    isActive: boolean;
    interval?: number;
}

export function DataSeeder({ isActive, interval = 5000 }: DataSeederProps) {
    const { useAddSensorData, useAddAIInsight, useVessels } = useMaritimeDatabase();
    const addSensorData = useAddSensorData();
    const addAIInsight = useAddAIInsight();
    const { data: vessels } = useVessels();
    const { toast } = useToast();

    // Keep track of simulated vessel state
    const [vesselState, setVesselState] = useState({
        lat: 42.3601,
        lng: -71.0589,
        heading: 45,
        fuel: 85,
        battery: 92
    });

    useEffect(() => {
        if (!isActive || !vessels || vessels.length === 0) return;

        const targetVesselId = vessels[0].id;

        const timer = setInterval(async () => {
            // 1. Simulate movement and sensor changes
            const newLat = vesselState.lat + (Math.random() - 0.5) * 0.001;
            const newLng = vesselState.lng + (Math.random() - 0.5) * 0.001;
            const newHeading = (vesselState.heading + (Math.random() - 0.5) * 10) % 360;
            const newFuel = Math.max(0, vesselState.fuel - 0.01);
            const newBattery = Math.max(0, vesselState.battery - 0.02);

            setVesselState({
                lat: newLat,
                lng: newLng,
                heading: newHeading,
                fuel: newFuel,
                battery: newBattery
            });

            // 2. Push Sensor Data
            try {
                await addSensorData.mutateAsync({
                    vessel_id: targetVesselId,
                    speed: 10 + Math.random() * 5,
                    heading: newHeading,
                    depth: 40 + Math.random() * 10,
                    water_temp: 18 + Math.random(),
                    wind_speed: 15 + Math.random() * 5,
                    wind_direction: (180 + Math.random() * 20) % 360,
                    battery_level: newBattery,
                    fuel_level: newFuel,
                    latitude: newLat,
                    longitude: newLng,
                    engine_rpm: 2000 + Math.random() * 200,
                    engine_temp: 85 + Math.random() * 5
                });

                // 3. Randomly push AI Insights (10% chance)
                if (Math.random() > 0.9) {
                    const insightTypes = ['prediction', 'recommendation', 'alert', 'optimization'] as const;
                    const type = insightTypes[Math.floor(Math.random() * insightTypes.length)];

                    await addAIInsight.mutateAsync({
                        vessel_id: targetVesselId,
                        type,
                        title: `Simulated ${type} Insight`,
                        description: 'This is a simulated insight generated by the Data Seeder for testing purposes.',
                        confidence: 70 + Math.random() * 25,
                        priority: Math.random() > 0.8 ? 'high' : 'medium',
                        data: { source: 'simulation' }
                    });
                }

            } catch (error) {
                console.error("Seeder Error:", error);
            }

        }, interval);

        return () => clearInterval(timer);
    }, [isActive, interval, vesselState, addSensorData, addAIInsight, vessels]);

    return null; // Invisible component
}
