// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://briqktywzjzkouhylrnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyaXFrdHl3emp6a291aHlscm52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTMxNjUsImV4cCI6MjA3MjAyOTE2NX0.TNYGEZ1AZVZSvGBLklZ0m2i6368j6O9oVmO-5DmlNDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});